title: "orbitalflower"
description: "orbitalflower"
author: "orbitalflower"
url: "https://orbitalflower.github.io"
defaultlicense: "CC BY"
#hitcounterid: "107279"

permalink: none

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-paginate
  - jemoji
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      published: false
    values:
      sitemap: false

category_emoji:
  comp: "💻"
  etc: "📦"
  games: "🕹️"
  opinion: "💬"
  rpg: "🎲"
  tv: "📺"
